feat: added log file streaming
tinyhttp/logger pull request #3
Opened 2023-05-17 18:40 UTC by aarontravass

As stated in #2 , this configuration will output logs to a file.

2023-05-27 18:09 UTC, talentlessguy requested changes

2023-05-27 18:09 UTC, talentlessguy commented on src/filelogger.ts
> +  private readonly dirname: string
use private property methods instead, aka `#dirname`

2023-05-27 18:09 UTC, talentlessguy commented on src/filelogger.ts
> +    if (existsSync(this.filename)) {
`existsSync` is deprecated, you should use `fs.access` API with a special code, I think it's `F_OK`

2023-05-27 21:39 UTC, aarontravass commented
I was getting this error during build
```typescript
> @tinyhttp/logger@1.3.4 build C:\Users\aaron\Documents\projects\logger
> rollup -c

(node:33272) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

src/index.ts → dist...
(!) Plugin typescript: @rollup/plugin-typescript TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
src/filelogger.ts: (9:5)

9     this.#dirname = directoryname(filename)
      ~~~~~~~~~~~~~

(!) Plugin typescript: @rollup/plugin-typescript: Rollup 'sourcemap' option must be set to generate source maps.
(!) Plugin typescript: @rollup/plugin-typescript: outputToFilesystem option is defaulting to true.
(!) Unresolved dependencies
https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
fs (imported by "src/filelogger.ts")
path (imported by "src/filelogger.ts")
created dist in 2.3s
```
hence I added tslib

2023-05-28 06:25 UTC, talentlessguy requested changes

2023-05-28 06:25 UTC, talentlessguy commented on package.json
> +    "install": "^0.13.0",
what's this dep?

2023-05-28 19:55 UTC, aarontravass commented on package.json
> +    "install": "^0.13.0",
got installed accidentally. weird.

2023-05-30 18:50 UTC, aarontravass commented
coverage is not stopping. hmm

2023-05-30 18:55 UTC, talentlessguy commented
@aarontravass there's a permission error for reading a file, please check your tests and make sure they don't reference any system files

2023-05-30 23:17 UTC, aarontravass commented
> @aarontravass there's a permission error for reading a file, please check your tests and make sure they don't reference any system files

it's a problem even on master https://github.com/tinyhttp/logger/actions/runs/5100346720/jobs/9168579370
Should I move tests to vitest?

2023-05-30 23:20 UTC, aarontravass commented
Let me take a look once again.

2023-05-31 18:09 UTC, aarontravass commented
ci passed :)

2023-05-31 19:39 UTC, merged